---
dn42_ownip: "172.22.145.169"
dn42_bandwidth: "23" # >= 10Mbps
dn42_region: "42" # North America-E
dn42_country: "1124" # Canada
dn42_ownipv6: "fd28:7515:7d51:9::1"

dn42_server_name: "ca-yto1.flap42.eu"
dn42_internal_id: 7

dn42_wireguard_privatekey: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          38313935346463666161326235303634316165323436653665343232306263636638366634663261
          3534383139633531343930623938313466336235663439320a306465326335356439636336376532
          66313962663536623136633331616233353932316565323237396435623530366533363935313865
          3362393433303139320a346135653437636366666334636632383030356561313035366363363031
          64383561613835623634353066636232373131363831663737636266306133346132353862653531
          3766626438316537633034613630363838393765663236376364
dn42_wireguard_publickey: "IkbCo1YSQBmYJ6Y8aGMD2d0doz2rcT6Z9R40iCVCw3E="

dn42_autopeer_wg_pub_key: ""
dn42_autopeer_wg_link_local_prefix: "fe80:5263::"
dn42_autopeer_wg_base_port: "52000"
dn42_autopeer_reserved_network: "2a11:6c7:2600:500::/56"
